spring.datasource.url=jdbc:postgresql://taskflow-db.cmb2wcecoxcd.us-east-1.rds.amazonaws.com:5432/taskflowdb
spring.datasource.username=taskflow
spring.datasource.password=TaskFlow123!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
